### ISSUE TITLE
Future plans for this repository?

### ISSUE THREAD

**Issue by rossmotley** [diablomedia/doctrine1#35]
I was curious about your future plans for this repository - there have been lots of changes for phpstan etc. and I wondered if you had any bigger plans beyond those changes?

**Comment by jaydiablo** [comment]
@rossmotley Not really, no.  We're doing a lot of static analysis on our own code-bases, and this is more effective if the libraries we use are documented correctly, which is why I've been doing psalm/phpstan analysis on this repo.

I may make a small modification to change the `@property` annotations that are generated on the base model classes to be more correct/valid (to help with static analysis in our own code), but other than that we'll probably just continue to make sure that Doctrine 1 continues to work with new PHP versions as they are released for as long as we're using this library (our ultimate goal is to move off of it, but that's a slow process).

**Comment by rossmotley** [comment]
@jaydiablo Thanks for the information, it sounds like a good goal.
