### ISSUE TITLE
Error with order by and mysql 5.7

### ISSUE THREAD

**Issue by franksl** [diablomedia/doctrine1#37]
Hello,
First of all, thanks for this repository, it's a life saver for an old project that I cannot move to new doctrine versions.
I have a problem with a complex query that involves many left joined models and the order by clause.
When running a select I receive an error like this:
"General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'erp.a7.descr' which is not in SELECT list; this is incompatible with DISTINCT"

Doing some research I noticed that this is due to some restrictions made in mysql 5.7 and this seems to be already handled in doctrine 2 (https://github.com/doctrine/doctrine2/issues/5622).

Do you think it can be fixed for this repo? 
Thanks,
Frank

**Comment by jaydiablo** [comment]
@franksl glad this repo has helped!

Could you provide a simplified test case where the error shows up (simple models and DQL necessary)?  That would be helpful for being able to create a test to be able to demonstrate that the error is resolved, and to prevent it from coming back.

I feel like we've also ran into this, but worked around it differently. I'll dig around a bit and see if I can find anything.

Thanks!

**Comment by franksl** [comment]
Hi,
Basically it happens when I have a 'master' table and a 'linked' table. I execute a "select * from master left join linked on some_field" and the add an 'order by' on a field in the linked table (this is what I think is the problem).
I'll try to reproduce the issue in a simple example as soon as I can.
Thanks

**Comment by jaydiablo** [comment]
Doing a bit of digging here, we're not on mysql 5.7 yet, which is probably why we haven't seen this happen.

Mysql has to have this setting in the `sql_mode` parameter: `ONLY_FULL_GROUP_BY` (which is the default since mysql 5.7.5 apparently)

And the query has to have `DISTINCT` in it (or perhaps some other mysql function/keyword, the documentation isn't clear what other keywords will trigger the error, but I haven't dug much).

Using some of the test models, I'm able to make Doctrine generate a query like this:

`SELECT a.id AS a__id FROM album a LEFT JOIN entity e ON a.user_id = e.id AND e.type = 0 ORDER BY e.name ASC;`

Which does not trigger the error since `DISTINCT` isn't present.  I can force the distinct in the DQL, like so:

```php
$q->select('DISTINCT a.id')
              ->from('Album a')
              ->leftJoin('a.User u')
              ->orderby('u.name ASC')
              ->limit(1);
```

Which makes this sql query:

`SELECT DISTINCT a.id AS a__id FROM album a LEFT JOIN entity e ON a.user_id = e.id AND e.type = 0 ORDER BY e.name ASC LIMIT 1`

Which does trigger the error.

I know that doctrine does add `DISTINCT` in certain conditions, and in those queries I think it also removes other columns from the select (just looking at some mysql query logs in our systems).

**Comment by franksl** [comment]
The case is exactly the one you are testing, doctrine adds a DISTINCT clause even to my queries, probably to exclude duplicate records that can happen with joins. Unfortunately it does not add to the select clause the field(s) in the ORDER BY clause so mysql 5.7 throws the error. Being on a third party hosting I cannot tweak the mysql options unfortunately.
Thanks,
Frank

**Comment by jaydiablo** [comment]
I tested one of our apps against 5.7 with that option enabled, and I do see failures due to the error you mention, but I also see other failures of this type:

>SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.table.column' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by.

This one seems harder to fix in Doctrine (I think it's probably something we can fix in our app).

I was able to make a very small change to Doctrine to fix the limit subquery that Doctrine builds when fetching relationships, and that fixed all of the `ORDER BY` errors, which I believe would fix your issue as well.

Doctrine already has the logic to make sure any columns in the `ORDER BY` are added to the `SELECT`, but it only does this for certain adapters (oracle, mssql, pgsql) and not for mysql. Adding mysql to the list fixes it (in my limited testing).  I want to be sure this isn't harmful to change across the board (mysql < 5.7), so I'll do more testing.

Are you able to change the doctrine files in a dev/test environment where you're seeing the error?  I can show you what needs to be changed (or even push a branch that you can point composer to).

**Comment by franksl** [comment]
That would be great! I can test the changes on my dev machine, if you can post the diff  or describe the changes here I'll apply to my code.
thanks
Frank

**Comment by jaydiablo** [comment]
In `lib/Doctrine/Query.php` change this line: https://github.com/diablomedia/doctrine1/blob/master/lib/Doctrine/Query.php#L1444

```php
if ($driverName == 'pgsql' || $driverName == 'oracle' || $driverName == 'oci' || $driverName == 'mssql' || $driverName == 'odbc') {
```

To this:

```php
if ($driverName == 'mysql' || $driverName == 'pgsql' || $driverName == 'oracle' || $driverName == 'oci' || $driverName == 'mssql' || $driverName == 'odbc') {
```

(Just adding the mysql drivername to the list)

Let me know how that goes :)

**Comment by jaydiablo** [comment]
Great!

I tested our apps with that change against mysql 5.6 and it doesn't seem to have any adverse effects.

I'll plan to get that change into the next release.
