### ISSUE TITLE
New release with "continue" inside "switch" fixes?

### ISSUE THREAD

**Issue by staticall** [diablomedia/doctrine1#52]
Good day!

Can you please tell, do you have any plans for a new release? I'm asking because we're trying to migrate a project to PHP 7.3 (it uses this package as dependency) and encountered some minor issues with "continue" inside "switch" (mostly inside Query\Tokenizer). I see that it's fixed already in the repo, but not published to packagist yet.

Thank you for the work you're doing!

**Comment by jaydiablo** [comment]
@staticall I just released version 3.0.0 which contains the "continue inside switch" fix: https://github.com/diablomedia/doctrine1/releases/tag/v3.0.0

As described in the release notes, the reason for the major version bump is due to the change in the YAML parsing library, so be sure to test against any YAML files that Doctrine would be reading (typically this is just a schema.yml file and fixtures, if you use them).  Worst case (in our testing) is that it will throw exceptions when parsing YAML that `sfYaml` would just ignore (duplicate keys, unquoted strings that start with `%` and characters outside of quotes that shouldn't be there).

**Comment by staticall** [comment]
Great news, thank you for this release!
